# .gitpod.yml
tasks:
  - init: |
      # Install Ruby dependencies
      bundle install
      # Run the automation script
      ./gitpod/automations/init.sh

  - command: |
      # Start the Ruby application
      ruby your_file.rb

# Download Dockerfile and devcontainer.json files
curl -Slo .devcontainer/Dockerfile https://raw.githubusercontent.com/devcontainers/images/main/src/javascript-node/.devcontainer/Dockerfile

curl -Slo .devcontainer/devcontainer.json https://raw.githubusercontent.com/devcontainers/images/main/src/javascript-node/.devcontainer/devcontainer.json

# rebuild the dev container
gitpod env devcontainer rebuild
